[package]
name = "k26-default-bitstreams"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
tokio = { version = "1.46.0", features = ["full"] }
zbus = { version = "5.8.0", default-features = false, features = ["tokio"] }