name: k26-default-bitstreams
base: core24
adopt-info: version
summary: Load a default bitstream to fpga device on boot
description: |
  This snap applicaiton connects with fpgad to load a bitstream to the fpga0 device.
  The contained bitstream is a fan controller for the K*26* series of Xilinx boards.
grade: devel
confinement: strict
plugs:
  fpgad-dbus:
    interface: dbus
    bus: system
    name: com.canonical.fpgad
slots:
  bitstreams:
    interface: content
    source:
      read: $SNAP/data
apps:
  k26-default-bitstreams:
    command: bin/k26-default-bitstreams
    daemon: oneshot
    plugs:
      - fpgad-dbus
    restart-condition: always .github/workflows/integration_tests.yaml.yml
    start-timeout: 30s
parts:
  version:
    plugin: nil
    source: .
    build-snaps:
      - jq
    override-pull: |
      craftctl default
      cargo_version=$(cargo metadata --no-deps --format-version 1 | jq -r .packages[0].version)
      craftctl set version="$cargo_version+git$(date +'%Y%m%d').$(git describe --always --exclude '*')"
  k26-default-bitstreams:
    plugin: rust
    source: .
  bitstream-data:
    plugin: dump
    source: https://github.com/Xilinx/kria-base-firmware
    source-type: git
    override-build: |-
      echo $(ls -a)
      mkdir -p $SNAPCRAFT_PART_INSTALL/data/k26-starter-kits
      cp k26_starter_kits/k26_starter_kits.bit $SNAPCRAFT_PART_INSTALL/data/k26-starter-kits/k26_starter_kits.bit.bin
      cp LICENSE-BINARIES $SNAPCRAFT_PART_INSTALL/data/k26-starter-kits/
