name: k26-default-bitstreams
base: core24
adopt-info: version
summary: Load a default bitstream to fpga device on boot
description: |
  This snap application connects with fpgad to load a bitstream to the fpga0 device.
  The contained bitstream is a fan controller for the K*26* series of Xilinx boards.
grade: devel
icon: snap/assets/icon.svg
source-code:
  - https://github.com/canonical/k26-default-bitstreams
license: GPL-3.0
issues:
  - https://github.com/canonical/k26-default-bitstreams/issues
confinement: strict
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  ppc64el:
    build-on: [ppc64el]
    build-for: [ppc64el]
  riscv64:
    build-on: [riscv64]
    build-for: [riscv64]
plugs:
  fpgad-dbus:
    interface: dbus
    bus: system
    name: com.canonical.fpgad
slots:
  provided-content:
    interface: content
    content: provider-content
    source:
      read:
        - $SNAP/data/k26-starter-kits
apps:
  k26-default-bitstreams:
    command: bin/k26-default-bitstreams
    daemon: oneshot
    plugs:
      - fpgad-dbus
    restart-condition: always
    start-timeout: 30s
    install-mode: disable
parts:
  version:
    plugin: nil
    source: .
    build-snaps:
      - jq
    override-pull: |
      craftctl default
      cargo_version=$(cargo metadata --no-deps --format-version 1 | jq -r .packages[0].version)
      craftctl set version="$cargo_version+git$(date +'%Y%m%d').$(git describe --always --exclude '*')"
  k26-default-bitstreams:
    plugin: rust
    source: .
    rust-channel: 'stable'
    rust-path:
      - k26-default-bitstreams
  bitstream-data:
    plugin: dump
    source: https://github.com/Xilinx/kria-base-firmware
    source-type: git
    build-packages:
      - xilinx-bootgen
    override-build: |
      cd k26_starter_kits && bootgen -image k26_starter_kits.bif -arch zynqmp -o k26_starter_kits.bit.bin -w && cd ../
      mkdir -p $SNAPCRAFT_PART_INSTALL/data/k26-starter-kits
      cp k26_starter_kits/k26_starter_kits.bit.bin $SNAPCRAFT_PART_INSTALL/data/k26-starter-kits/
      cp LICENSE-BINARIES $SNAPCRAFT_PART_INSTALL/data/k26-starter-kits/